export const masks = {
	AF: { name: 'Afghanistan', iso2: 'AF', cc: '+93', mask: '+93 ## ### ####' },
	AX: { name: 'Aland Islands', iso2: 'AX', cc: '+358', mask: '+358 ## ### ####' },
	AL: { name: 'Albania', iso2: 'AL', cc: '+355', mask: '+355 ## ### ####' },
	DZ: { name: 'Algeria', iso2: 'DZ', cc: '+213', mask: '+213 ## ### ## ##' },
	AS: { name: 'American Samoa', iso2: 'AS', cc: '+1', mask: '+1 (684) ###-####' },
	AD: { name: 'Andorra', iso2: 'AD', cc: '+376', mask: '+376 ### ###' },
	AO: { name: 'Angola', iso2: 'AO', cc: '+244', mask: '+244 ### ### ###' },
	AI: { name: 'Anguilla', iso2: 'AI', cc: '+1', mask: '+1 (264) ###-####' },
	AQ: { name: 'Antarctica', iso2: 'AQ', cc: '+672', mask: '+672 1 ## ###' },
	AG: { name: 'Antigua And Barbuda', iso2: 'AG', cc: '+1', mask: '+1 (268) ###-####' },
	AR: { name: 'Argentina', iso2: 'AR', cc: '+54', mask: '+54 9 ## ###-####' },
	AM: { name: 'Armenia', iso2: 'AM', cc: '+374', mask: '+374 ## ### ###' },
	AW: { name: 'Aruba', iso2: 'AW', cc: '+297', mask: '+297 ### ####' },
	AU: { name: 'Australia', iso2: 'AU', cc: '+61', mask: '+61 # #### ####' },
	AT: { name: 'Austria', iso2: 'AT', cc: '+43', mask: '+43 ## ### ####' },
	AZ: { name: 'Azerbaijan', iso2: 'AZ', cc: '+994', mask: '+994 ## ### ## ##' },
	BS: { name: 'Bahamas', iso2: 'BS', cc: '+1', mask: '+1 (242) ###-####' },
	BH: { name: 'Bahrain', iso2: 'BH', cc: '+973', mask: '+973 #### ####' },
	BD: { name: 'Bangladesh', iso2: 'BD', cc: '+880', mask: '+880 # ### ###[#]' },
	BB: { name: 'Barbados', iso2: 'BB', cc: '+1', mask: '+1 (246) ###-####' },
	BY: { name: 'Belarus', iso2: 'BY', cc: '+375', mask: '+375 (##) ###-##-##' },
	BE: { name: 'Belgium', iso2: 'BE', cc: '+32', mask: '+32 # ### ## ##' },
	BZ: { name: 'Belize', iso2: 'BZ', cc: '+501', mask: '+501 ###-####' },
	BJ: { name: 'Benin', iso2: 'BJ', cc: '+229', mask: '+229 ## ## ####' },
	BM: { name: 'Bermuda', iso2: 'BM', cc: '+1', mask: '+1 (441) ###-####' },
	BT: { name: 'Bhutan', iso2: 'BT', cc: '+975', mask: '+975 # ### ###' },
	BO: { name: 'Bolivia', iso2: 'BO', cc: '+591', mask: '+591 # ### ####' },
	BA: { name: 'Bosnia And Herzegovina', iso2: 'BA', cc: '+387', mask: '+387 ## ###-###[#]' },
	BW: { name: 'Botswana', iso2: 'BW', cc: '+267', mask: '+267 ## ### ###' },
	BV: { name: 'Bouvet Island', iso2: 'BV', cc: '+47', mask: '+47 ### ## ###' },
	BR: { name: 'Brazil', iso2: 'BR', cc: '+55', mask: '+55 ## #### ####[#]' },
	IO: { name: 'British Indian Ocean Territory', iso2: 'IO', cc: '+246', mask: '+246 ### ####' },
	BN: { name: 'Brunei Darussalam', iso2: 'BN', cc: '+673', mask: '+673 ### ####' },
	BG: { name: 'Bulgaria', iso2: 'BG', cc: '+359', mask: '+359 ## ### ####' },
	BF: { name: 'Burkina Faso', iso2: 'BF', cc: '+226', mask: '+226 ## ## ####' },
	BI: { name: 'Burundi', iso2: 'BI', cc: '+257', mask: '+257 ## ## ####' },
	KH: { name: 'Cambodia', iso2: 'KH', cc: '+855', mask: '+855 ## ### ###' },
	CM: { name: 'Cameroon', iso2: 'CM', cc: '+237', mask: '+237 # ## ## ## ##' },
	CA: { name: 'Canada', iso2: 'CA', cc: '+1', mask: '+1 (###) ###-####' },
	CV: { name: 'Cape Verde', iso2: 'CV', cc: '+238', mask: '+238 (##) ## ##' },
	KY: { name: 'Cayman Islands', iso2: 'KY', cc: '+1', mask: '+1 (345) ###-####' },
	CF: { name: 'Central African Republic', iso2: 'CF', cc: '+236', mask: '+236 ## ## ####' },
	TD: { name: 'Chad', iso2: 'TD', cc: '+235', mask: '+235 ## ## ## ##' },
	CL: { name: 'Chile', iso2: 'CL', cc: '+56', mask: '+56 # #### ####' },
	CN: { name: 'China', iso2: 'CN', cc: '+86', mask: '+86 ## #### ####' },
	CX: { name: 'Christmas Island', iso2: 'CX', cc: '+61', mask: '+61 4 ## ### ###' },
	CC: { name: 'Cocos (Keeling) Islands', iso2: 'CC', cc: '+61', mask: '+61 4 ## ### ###' },
	CO: { name: 'Colombia', iso2: 'CO', cc: '+57', mask: '+57 # ### ####' },
	KM: { name: 'Comoros', iso2: 'KM', cc: '+269', mask: '+269 ## ## ##' },
	CG: { name: 'Congo', iso2: 'CG', cc: '+242', mask: '+242 ## ### ####' },
	CD: { name: 'Congo, Democratic Republic', iso2: 'CD', cc: '+243', mask: '+243 ## ### ####' },
	CK: { name: 'Cook Islands', iso2: 'CK', cc: '+682', mask: '+682 ## ###' },
	CR: { name: 'Costa Rica', iso2: 'CR', cc: '+506', mask: '+506 #### ####' },
	CI: { name: "Cote D'Ivoire", iso2: 'CI', cc: '+225', mask: '+225 ## ## ## ##' },
	HR: { name: 'Croatia', iso2: 'HR', cc: '+385', mask: '+385 # ### ####' },
	CU: { name: 'Cuba', iso2: 'CU', cc: '+53', mask: '+53 # ### ####' },
	CY: { name: 'Cyprus', iso2: 'CY', cc: '+357', mask: '+357 ## ### ###' },
	CZ: { name: 'Czech Republic', iso2: 'CZ', cc: '+420', mask: '+420 ### ### ###' },
	DK: { name: 'Denmark', iso2: 'DK', cc: '+45', mask: '+45 ## ## ## ##' },
	DJ: { name: 'Djibouti', iso2: 'DJ', cc: '+253', mask: '+253 ## ## ## ##' },
	DM: { name: 'Dominica', iso2: 'DM', cc: '+1', mask: '+1 (767) ###-####' },
	DO: { name: 'Dominican Republic', iso2: 'DO', cc: '+1', mask: '+1 (###) ###-####' },
	EC: { name: 'Ecuador', iso2: 'EC', cc: '+593', mask: '+593 ## ### ####' },
	EG: { name: 'Egypt', iso2: 'EG', cc: '+20', mask: '+20 # #### ####' },
	SV: { name: 'El Salvador', iso2: 'SV', cc: '+503', mask: '+503 #### ####' },
	GQ: { name: 'Equatorial Guinea', iso2: 'GQ', cc: '+240', mask: '+240 ## ### ####' },
	ER: { name: 'Eritrea', iso2: 'ER', cc: '+291', mask: '+291 # ### ###' },
	EE: { name: 'Estonia', iso2: 'EE', cc: '+372', mask: '+372 #### ####' },
	ET: { name: 'Ethiopia', iso2: 'ET', cc: '+251', mask: '+251 ## ### ####' },
	FK: { name: 'Falkland Islands (Malvinas)', iso2: 'FK', cc: '+500', mask: '+500 #####' },
	FO: { name: 'Faroe Islands', iso2: 'FO', cc: '+298', mask: '+298 ######' },
	FJ: { name: 'Fiji', iso2: 'FJ', cc: '+679', mask: '+679 ### ####' },
	FI: { name: 'Finland', iso2: 'FI', cc: '+358', mask: '+358 ## ### ####' },
	FR: { name: 'France', iso2: 'FR', cc: '+33', mask: '+33 # ## ## ## ##' },
	GF: { name: 'French Guiana', iso2: 'GF', cc: '+594', mask: '+594 ##### ####' },
	PF: { name: 'French Polynesia', iso2: 'PF', cc: '+689', mask: '+689 ## ## ##' },
	TF: { name: 'French Southern Territories', iso2: 'TF', cc: '+262', mask: '+262 ##### ####' },
	GA: { name: 'Gabon', iso2: 'GA', cc: '+241', mask: '+241 # ## ## ##' },
	GM: { name: 'Gambia', iso2: 'GM', cc: '+220', mask: '+220 ### ####' },
	GE: { name: 'Georgia', iso2: 'GE', cc: '+995', mask: '+995 ## ### ####' },
	DE: { name: 'Germany', iso2: 'DE', cc: '+49', mask: '+49 ## ######' },
	GH: { name: 'Ghana', iso2: 'GH', cc: '+233', mask: '+233 ## ### ####' },
	GI: { name: 'Gibraltar', iso2: 'GI', cc: '+350', mask: '+350 200 #####' },
	GR: { name: 'Greece', iso2: 'GR', cc: '+30', mask: '+30 ## ### ####' },
	GL: { name: 'Greenland', iso2: 'GL', cc: '+299', mask: '+299 ## ## ##' },
	GD: { name: 'Grenada', iso2: 'GD', cc: '+1', mask: '+1 (473) ###-####' },
	GP: { name: 'Guadeloupe', iso2: 'GP', cc: '+590', mask: '+590 #### ####' },
	GU: { name: 'Guam', iso2: 'GU', cc: '+1', mask: '+1 (671) ###-####' },
	GT: { name: 'Guatemala', iso2: 'GT', cc: '+502', mask: '+502 # ### ####' },
	GG: { name: 'Guernsey', iso2: 'GG', cc: '+44', mask: '+44 1481 ## ####' },
	GN: { name: 'Guinea', iso2: 'GN', cc: '+224', mask: '+224 ## ### ####' },
	GW: { name: 'Guinea-Bissau', iso2: 'GW', cc: '+245', mask: '+245 # ### ###' },
	GY: { name: 'Guyana', iso2: 'GY', cc: '+592', mask: '+592 ### ####' },
	HT: { name: 'Haiti', iso2: 'HT', cc: '+509', mask: '+509 ## ## ####' },
	HM: { name: 'Heard Island & Mcdonald Islands', iso2: 'HM', cc: '+672', mask: '+672 1 ## ###' },
	VA: { name: 'Holy See (Vatican City State)', iso2: 'VA', cc: '+39', mask: '+39 06 698 #####' },
	HN: { name: 'Honduras', iso2: 'HN', cc: '+504', mask: '+504 #### ####' },
	HK: { name: 'Hong Kong', iso2: 'HK', cc: '+852', mask: '+852 #### ####' },
	HU: { name: 'Hungary', iso2: 'HU', cc: '+36', mask: '+36 #[#] ### ###[#]' },
	IS: { name: 'Iceland', iso2: 'IS', cc: '+354', mask: '+354 ### ####' },
	IN: { name: 'India', iso2: 'IN', cc: '+91', mask: '+91 ## #### ####' },
	ID: { name: 'Indonesia', iso2: 'ID', cc: '+62', mask: '+62 ## #### ####' },
	IR: { name: 'Iran, Islamic Republic Of', iso2: 'IR', cc: '+98', mask: '+98 ## #### ####' },
	IQ: { name: 'Iraq', iso2: 'IQ', cc: '+964', mask: '+964 ## ### ####' },
	IE: { name: 'Ireland', iso2: 'IE', cc: '+353', mask: '+353 ## ### ####' },
	IM: { name: 'Isle Of Man', iso2: 'IM', cc: '+44', mask: '+44 1624 ######' },
	IL: { name: 'Israel', iso2: 'IL', cc: '+972', mask: '+972 # ### ####' },
	IT: { name: 'Italy', iso2: 'IT', cc: '+39', mask: '+39 ## #### ####' },
	JM: { name: 'Jamaica', iso2: 'JM', cc: '+1', mask: '+1 (876) ###-####' },
	JP: { name: 'Japan', iso2: 'JP', cc: '+81', mask: '+81 ##-####-####' },
	JE: { name: 'Jersey', iso2: 'JE', cc: '+44', mask: '+44 1534 ######' },
	JO: { name: 'Jordan', iso2: 'JO', cc: '+962', mask: '+962 # #### ####' },
	KZ: { name: 'Kazakhstan', iso2: 'KZ', cc: '+7', mask: '+7 700 ### ####' },
	KE: { name: 'Kenya', iso2: 'KE', cc: '+254', mask: '+254 ## #######' },
	KI: { name: 'Kiribati', iso2: 'KI', cc: '+686', mask: '+686 ## ###' },
	KR: { name: 'Korea', iso2: 'KR', cc: '+82', mask: '+82 ##-####-####' },
	KW: { name: 'Kuwait', iso2: 'KW', cc: '+965', mask: '+965 #### ####' },
	KG: { name: 'Kyrgyzstan', iso2: 'KG', cc: '+996', mask: '+996 ## ### ####' },
	LA: { name: "Lao People's Democratic Republic", iso2: 'LA', cc: '+856', mask: '+856 ## ### ###' },
	LV: { name: 'Latvia', iso2: 'LV', cc: '+371', mask: '+371 #### ####' },
	LB: { name: 'Lebanon', iso2: 'LB', cc: '+961', mask: '+961 # ### ###' },
	LS: { name: 'Lesotho', iso2: 'LS', cc: '+266', mask: '+266 # ### ####' },
	LR: { name: 'Liberia', iso2: 'LR', cc: '+231', mask: '+231 ## ### ###' },
	LY: { name: 'Libyan Arab Jamahiriya', iso2: 'LY', cc: '+218', mask: '+218 ## ### ####' },
	LI: { name: 'Liechtenstein', iso2: 'LI', cc: '+423', mask: '+423 ### ####' },
	LT: { name: 'Lithuania', iso2: 'LT', cc: '+370', mask: '+370 ### #####' },
	LU: { name: 'Luxembourg', iso2: 'LU', cc: '+352', mask: '+352 ### ### ###' },
	MO: { name: 'Macao', iso2: 'MO', cc: '+853', mask: '+853 #### ####' },
	MK: { name: 'Macedonia', iso2: 'MK', cc: '+389', mask: '+389 ## ### ###' },
	MG: { name: 'Madagascar', iso2: 'MG', cc: '+261', mask: '+261 ## ## #####' },
	MW: { name: 'Malawi', iso2: 'MW', cc: '+265', mask: '+265 # ### ####' },
	MY: { name: 'Malaysia', iso2: 'MY', cc: '+60', mask: '+60 ##-### ####' },
	MV: { name: 'Maldives', iso2: 'MV', cc: '+960', mask: '+960 ###-####' },
	ML: { name: 'Mali', iso2: 'ML', cc: '+223', mask: '+223 ## ## ####' },
	MT: { name: 'Malta', iso2: 'MT', cc: '+356', mask: '+356 #### ####' },
	MH: { name: 'Marshall Islands', iso2: 'MH', cc: '+692', mask: '+692 ###-####' },
	MQ: { name: 'Martinique', iso2: 'MQ', cc: '+596', mask: '+596 ### ## ##' },
	MR: { name: 'Mauritania', iso2: 'MR', cc: '+222', mask: '+222 ## ## ####' },
	MU: { name: 'Mauritius', iso2: 'MU', cc: '+230', mask: '+230 ### ####' },
	YT: { name: 'Mayotte', iso2: 'YT', cc: '+262', mask: '+262 ##### ####' },
	MX: { name: 'Mexico', iso2: 'MX', cc: '+52', mask: '+52 ## #### ####' },
	FM: { name: 'Micronesia, Federated States Of', iso2: 'FM', cc: '+691', mask: '+691 ### ####' },
	MD: { name: 'Moldova', iso2: 'MD', cc: '+373', mask: '+373 #### ####' },
	MC: { name: 'Monaco', iso2: 'MC', cc: '+377', mask: '+377 ## ## ## ##' },
	MN: { name: 'Mongolia', iso2: 'MN', cc: '+976', mask: '+976 ## ## ####' },
	ME: { name: 'Montenegro', iso2: 'ME', cc: '+382', mask: '+382 ## ### ###' },
	MS: { name: 'Montserrat', iso2: 'MS', cc: '+1', mask: '+1 (664) ###-####' },
	MA: { name: 'Morocco', iso2: 'MA', cc: '+212', mask: '+212 ## #### ####' },
	MZ: { name: 'Mozambique', iso2: 'MZ', cc: '+258', mask: '+258 ## ### ###' },
	MM: { name: 'Myanmar', iso2: 'MM', cc: '+95', mask: '+95 ## ### ###' },
	NA: { name: 'Namibia', iso2: 'NA', cc: '+264', mask: '+264 ## ### ####' },
	NR: { name: 'Nauru', iso2: 'NR', cc: '+674', mask: '+674 ### ####' },
	NP: { name: 'Nepal', iso2: 'NP', cc: '+977', mask: '+977 ## ### ####' },
	NL: { name: 'Netherlands', iso2: 'NL', cc: '+31', mask: '+31 ## ### ####' },
	NC: { name: 'New Caledonia', iso2: 'NC', cc: '+687', mask: '+687 ## ####' },
	NZ: { name: 'New Zealand', iso2: 'NZ', cc: '+64', mask: '+64 # ### ####' },
	NI: { name: 'Nicaragua', iso2: 'NI', cc: '+505', mask: '+505 #### ####' },
	NE: { name: 'Niger', iso2: 'NE', cc: '+227', mask: '+227 ## ## ####' },
	NG: { name: 'Nigeria', iso2: 'NG', cc: '+234', mask: '+234 ## ### ####' },
	NU: { name: 'Niue', iso2: 'NU', cc: '+683', mask: '+683 ####' },
	NF: { name: 'Norfolk Island', iso2: 'NF', cc: '+672', mask: '+672 ## ###' },
	MP: { name: 'Northern Mariana Islands', iso2: 'MP', cc: '+1', mask: '+1 (670) ###-####' },
	NO: { name: 'Norway', iso2: 'NO', cc: '+47', mask: '+47 ## ## ## ##' },
	OM: { name: 'Oman', iso2: 'OM', cc: '+968', mask: '+968 #### ####' },
	PK: { name: 'Pakistan', iso2: 'PK', cc: '+92', mask: '+92 ## ### ####' },
	PW: { name: 'Palau', iso2: 'PW', cc: '+680', mask: '+680 ### ####' },
	PS: { name: 'Palestinian Territory, Occupied', iso2: 'PS', cc: '+970', mask: '+970 ## ### ####' },
	PA: { name: 'Panama', iso2: 'PA', cc: '+507', mask: '+507 ### ####' },
	PG: { name: 'Papua New Guinea', iso2: 'PG', cc: '+675', mask: '+675 ## ### ###' },
	PY: { name: 'Paraguay', iso2: 'PY', cc: '+595', mask: '+595 ## ### ####' },
	PE: { name: 'Peru', iso2: 'PE', cc: '+51', mask: '+51 ## ### ###' },
	PH: { name: 'Philippines', iso2: 'PH', cc: '+63', mask: '+63 ## ### ####' },
	PN: { name: 'Pitcairn', iso2: 'PN', cc: '+64', mask: '+64 ## ### ####' },
	PL: { name: 'Poland', iso2: 'PL', cc: '+48', mask: '+48 ## ### ####' },
	PT: { name: 'Portugal', iso2: 'PT', cc: '+351', mask: '+351 ## ### ####' },
	PR: { name: 'Puerto Rico', iso2: 'PR', cc: '+1', mask: '+1 (###) ###-####' },
	QA: { name: 'Qatar', iso2: 'QA', cc: '+974', mask: '+974 #### ####' },
	RE: { name: 'Reunion', iso2: 'RE', cc: '+262', mask: '+262 ##### ####' },
	RO: { name: 'Romania', iso2: 'RO', cc: '+40', mask: '+40 ## ### ####' },
	RU: { name: 'Russian Federation', iso2: 'RU', cc: '+7', mask: '+7 (###) ###-##-##' },
	RW: { name: 'Rwanda', iso2: 'RW', cc: '+250', mask: '+250 ## ### ###' },
	BL: { name: 'Saint Barthelemy', iso2: 'BL', cc: '+590', mask: '+590 ### ####' },
	SH: { name: 'Saint Helena', iso2: 'SH', cc: '+290', mask: '+290 ####' },
	KN: { name: 'Saint Kitts And Nevis', iso2: 'KN', cc: '+1', mask: '+1 (869) ###-####' },
	LC: { name: 'Saint Lucia', iso2: 'LC', cc: '+1', mask: '+1 (758) ###-####' },
	MF: { name: 'Saint Martin', iso2: 'MF', cc: '+590', mask: '+590 ### ####' },
	PM: { name: 'Saint Pierre And Miquelon', iso2: 'PM', cc: '+508', mask: '+508 ## ## ##' },
	VC: { name: 'Saint Vincent And Grenadines', iso2: 'VC', cc: '+1', mask: '+1 (784) ###-####' },
	WS: { name: 'Samoa', iso2: 'WS', cc: '+685', mask: '+685 ## ####' },
	SM: { name: 'San Marino', iso2: 'SM', cc: '+378', mask: '+378 #### ######' },
	ST: { name: 'Sao Tome And Principe', iso2: 'ST', cc: '+239', mask: '+239 ## ## ##' },
	SA: { name: 'Saudi Arabia', iso2: 'SA', cc: '+966', mask: '+966 # #### ####' },
	SN: { name: 'Senegal', iso2: 'SN', cc: '+221', mask: '+221 ## ### ####' },
	RS: { name: 'Serbia', iso2: 'RS', cc: '+381', mask: '+381 ## #### ###' },
	SC: { name: 'Seychelles', iso2: 'SC', cc: '+248', mask: '+248 # ### ###' },
	SL: { name: 'Sierra Leone', iso2: 'SL', cc: '+232', mask: '+232 ## ######' },
	SG: { name: 'Singapore', iso2: 'SG', cc: '+65', mask: '+65 #### ####' },
	SK: { name: 'Slovakia', iso2: 'SK', cc: '+421', mask: '+421 [##]# ### ####' },
	SI: { name: 'Slovenia', iso2: 'SI', cc: '+386', mask: '+386 # ### ## ##' },
	SB: { name: 'Solomon Islands', iso2: 'SB', cc: '+677', mask: '+677 #####' },
	SO: { name: 'Somalia', iso2: 'SO', cc: '+252', mask: '+252 # ### ###' },
	ZA: { name: 'South Africa', iso2: 'ZA', cc: '+27', mask: '+27 ## ### ####' },
	GS: { name: 'South Georgia And Sandwich Isl.', iso2: 'GS', cc: '+500', mask: '+500 #####' },
	ES: { name: 'Spain', iso2: 'ES', cc: '+34', mask: '+34 ### ### ###' },
	LK: { name: 'Sri Lanka', iso2: 'LK', cc: '+94', mask: '+94 ## ### ####' },
	SD: { name: 'Sudan', iso2: 'SD', cc: '+249', mask: '+249 ## ### ####' },
	SR: { name: 'Suriname', iso2: 'SR', cc: '+597', mask: '+597 ### ###' },
	SJ: { name: 'Svalbard And Jan Mayen', iso2: 'SJ', cc: '+47', mask: '+47 ### ## ###' },
	SZ: { name: 'Swaziland', iso2: 'SZ', cc: '+268', mask: '+268 ## ## ####' },
	SE: { name: 'Sweden', iso2: 'SE', cc: '+46', mask: '+46 ## ### ####' },
	CH: { name: 'Switzerland', iso2: 'CH', cc: '+41', mask: '+41 ## ### ####' },
	SY: { name: 'Syrian Arab Republic', iso2: 'SY', cc: '+963', mask: '+963 ## #### ###' },
	TW: { name: 'Taiwan', iso2: 'TW', cc: '+886', mask: '+886 # #### ####' },
	TJ: { name: 'Tajikistan', iso2: 'TJ', cc: '+992', mask: '+992 ## ### ####' },
	TZ: { name: 'Tanzania', iso2: 'TZ', cc: '+255', mask: '+255 ## ### ####' },
	TH: { name: 'Thailand', iso2: 'TH', cc: '+66', mask: '+66 # #### ####' },
	TL: { name: 'Timor-Leste', iso2: 'TL', cc: '+670', mask: '+670 ### ####' },
	TG: { name: 'Togo', iso2: 'TG', cc: '+228', mask: '+228 ## ### ###' },
	TK: { name: 'Tokelau', iso2: 'TK', cc: '+690', mask: '+690 ####' },
	TO: { name: 'Tonga', iso2: 'TO', cc: '+676', mask: '+676 ## ###' },
	TT: { name: 'Trinidad And Tobago', iso2: 'TT', cc: '+1', mask: '+1 (868) ###-####' },
	TN: { name: 'Tunisia', iso2: 'TN', cc: '+216', mask: '+216 ## ### ###' },
	TR: { name: 'Turkey', iso2: 'TR', cc: '+90', mask: '+90 (###) ### ####' },
	TM: { name: 'Turkmenistan', iso2: 'TM', cc: '+993', mask: '+993 # ### ###' },
	TC: { name: 'Turks And Caicos Islands', iso2: 'TC', cc: '+1', mask: '+1 (649) ###-####' },
	TV: { name: 'Tuvalu', iso2: 'TV', cc: '+688', mask: '+688 ## ###' },
	UG: { name: 'Uganda', iso2: 'UG', cc: '+256', mask: '+256 [#]## ### ###' },
	UA: { name: 'Ukraine', iso2: 'UA', cc: '+380', mask: '+380 ## ### ####' },
	AE: { name: 'United Arab Emirates', iso2: 'AE', cc: '+971', mask: '+971 ## ### ## ##' },
	GB: { name: 'United Kingdom', iso2: 'GB', cc: '+44', mask: '+44 ## #### ####' },
	US: { name: 'United States', iso2: 'US', cc: '+1', mask: '+1 (###) ###-####' },
	UM: { name: 'United States Outlying Islands', iso2: 'UM', cc: 'N/A', mask: 'N/A' },
	UY: { name: 'Uruguay', iso2: 'UY', cc: '+598', mask: '+598 # ### ## ##' },
	UZ: { name: 'Uzbekistan', iso2: 'UZ', cc: '+998', mask: '+998 ## ### ####' },
	VU: { name: 'Vanuatu', iso2: 'VU', cc: '+678', mask: '+678 ## ####' },
	VE: { name: 'Venezuela', iso2: 'VE', cc: '+58', mask: '+58 ###-#######' },
	VN: { name: 'Viet Nam', iso2: 'VN', cc: '+84', mask: '+84 ## #### ###' },
	VG: { name: 'Virgin Islands, British', iso2: 'VG', cc: '+1', mask: '+1 (284) ###-####' },
	VI: { name: 'Virgin Islands, U.S.', iso2: 'VI', cc: '+1', mask: '+1 (340) ###-####' },
	WF: { name: 'Wallis And Futuna', iso2: 'WF', cc: '+681', mask: '+681 ## ####' },
	EH: { name: 'Western Sahara', iso2: 'EH', cc: '+212', mask: '+212 5288-#####' },
	YE: { name: 'Yemen', iso2: 'YE', cc: '+967', mask: '+967 # ### ###' },
	ZM: { name: 'Zambia', iso2: 'ZM', cc: '+260', mask: '+260 ## ### ####' },
	ZW: { name: 'Zimbabwe', iso2: 'ZW', cc: '+263', mask: '+263 # ######' }
};
